MESSAGES:
  ERRORS:
    START: Error starting the application

DATA_FILE: data/heloc_dataset_v1.csv

INPUT_VALUES:
  ExternalRiskEstimate:
    NAME: ExternalRiskEstimate
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 15
  AverageMInFile:
    NAME: AverageMInFile
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumSatisfactoryTrades:
    NAME: NumSatisfactoryTrades
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumTrades60Ever/DerogPubRec:
    NAME: NumTrades60Ever/DerogPubRec
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumTrades90Ever/DerogPubRec:
    NAME: NumTrades90Ever/DerogPubRec
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  PercentTradesNeverDelq:
    NAME: PercentTradesNeverDelq
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 100
  MSinceMostRecentDelq:
    NAME: MSinceMostRecentDelq
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  MaxDelq/PublicRecLast12M:
    NAME: MaxDelq/PublicRecLast12M
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  MaxDelqEver:
    NAME: MaxDelqEver
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumTotalTrades:
    NAME: NumTotalTrades
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumTradesOpeninLast12M:
    NAME: NumTradesOpeninLast12M
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  PercentInstallTrades:
    NAME: PercentInstallTrades
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 100
  MSinceMostRecentInqexcl7days:
    NAME: MSinceMostRecentInqexcl7days
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumInqLast6M:
    NAME: NumInqLast6M
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumInqLast6Mexcl7days:
    NAME: NumInqLast6Mexcl7days
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NetFractionRevolvingBurden:
    NAME: NetFractionRevolvingBurden
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 100
  NetFractionInstallBurden:
    NAME: NetFractionInstallBurden
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 100
  NumRevolvingTradesWBalance:
    NAME: NumRevolvingTradesWBalance
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumInstallTradesWBalance:
    NAME: NumInstallTradesWBalance
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  NumBank/NatlTradesWHighUtilization:
    NAME: NumBank/NatlTradesWHighUtilization
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  PercentTradesWBalance:
    NAME: PercentTradesWBalance
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 100
  MSinceOldestTradeOpen:
    NAME: MSinceOldestTradeOpen
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100
  MSinceMostRecentTradeOpen:
    NAME: MSinceMostRecentTradeOpen
    TYPE: INTEGER
    MIN: 0
    MAX: 1000
    DEFAULT: 100