MESSAGES:
  ERRORS:
    START: Error starting the application
    MODEL: Error loading the model, have you stored it locally?
    CF: Not able to find counterfactuals

SHOW_LOGS: False

MAX_CFS: 10

VISUALIZATION:
  COLORS:
    ref_bad: "#e7298a"
    ref_good: "#1b9e77"
    customer: "#7570b3"
    alternative: "#d95f02"
  DGRID:
    MAX_GLYPH_WIDTH: 10.0
    MAX_GLYPH_HEIGHT: 10.0
    MAX_DELTA: 200.0

DATA_FILE: data/heloc_dataset_v4.csv
MODEL_FILE: models/MainModel_v4.pkl

INPUT_VALUES:
  ExternalRiskEstimate:
    NAME: ExternalRiskEstimate
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 72
  MSinceMostRecentTradeOpen:
    NAME: MSinceMostRecentTradeOpen
    TYPE: INTEGER
    MIN: 0
    MAX: 300
    DEFAULT: 6
  AverageMInFile:
    NAME: AverageMInFile
    TYPE: INTEGER
    MIN: 0
    MAX: 350
    DEFAULT: 76
  NumSatisfactoryTrades:
    NAME: NumSatisfactoryTrades
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 20
  NumTrades60Ever/DerogPubRec:
    NAME: NumTrades60Ever/DerogPubRec
    TYPE: INTEGER
    MIN: 0
    MAX: 20
    DEFAULT: 0
  NumTrades90Ever/DerogPubRec:
    NAME: NumTrades90Ever/DerogPubRec
    TYPE: INTEGER
    MIN: 0
    MAX: 20
    DEFAULT: 0
  PercentTradesNeverDelq:
    NAME: PercentTradesNeverDelq
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 97
  # MSinceMostRecentDelq:
  #   NAME: MSinceMostRecentDelq
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 1000
  #   DEFAULT: 10
  # MaxDelq/PublicRecLast12M:
  #   NAME: MaxDelq/PublicRecLast12M
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 9
  #   DEFAULT: 6
  # MaxDelqEver:
  #   NAME: MaxDelqEver
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 8
  #   DEFAULT: 6
  NumTotalTrades:
    NAME: NumTotalTrades
    TYPE: INTEGER
    MIN: 0
    MAX: 150
    DEFAULT: 21
  NumTradesOpeninLast12M:
    NAME: NumTradesOpeninLast12M
    TYPE: INTEGER
    MIN: 0
    MAX: 25
    DEFAULT: 1
  PercentInstallTrades:
    NAME: PercentInstallTrades
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 33
  # MSinceMostRecentInqexcl7days:
  #   NAME: MSinceMostRecentInqexcl7days
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 50
  #   DEFAULT: 10
  NumInqLast6M:
    NAME: NumInqLast6M
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 1
  NumInqLast6Mexcl7days:
    NAME: NumInqLast6Mexcl7days
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 1
  NetFractionRevolvingBurden:
    NAME: NetFractionRevolvingBurden
    TYPE: INTEGER
    MIN: 0
    MAX: 300
    DEFAULT: 29
  # NetFractionInstallBurden:
  #   NAME: NetFractionInstallBurden
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 500
  #   DEFAULT: 10
  NumRevolvingTradesWBalance:
    NAME: NumRevolvingTradesWBalance
    TYPE: INTEGER
    MIN: 0
    MAX: 50
    DEFAULT: 3
  # NumInstallTradesWBalance:
  #   NAME: NumInstallTradesWBalance
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 50
  #   DEFAULT: 2
  # NumBank/NatlTradesWHighUtilization:
  #   NAME: NumBank/NatlTradesWHighUtilization
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 40
  #   DEFAULT: 10
  PercentTradesWBalance:
    NAME: PercentTradesWBalance
    TYPE: INTEGER
    MIN: 0
    MAX: 100
    DEFAULT: 67
  # MSinceOldestTradeOpen:
  #   NAME: MSinceOldestTradeOpen
  #   TYPE: INTEGER
  #   MIN: 0
  #   MAX: 1000
  #   DEFAULT: 30
  